maxretry = 3

[ups1]
    driver = nutdrv_qx
    port = auto
    vendorid = 0665
    productid = 5161
    bus = 005
    desc = "First UPS"
    default.battery.voltage.low = 21.0
    default.battery.voltage.high = 25.2
    default.battery.voltage.nominal = 24.0
    override.ups.power.nominal = 2000
    override.ups.realpower.nominal = 1200

[ups2]
    driver = nutdrv_qx
    port = auto
    vendorid = 0665
    productid = 5161
    bus = 006
    desc = "Second UPS"
    default.battery.voltage.low = 21.0
    default.battery.voltage.high = 25.2
    default.battery.voltage.nominal = 24.0
    override.ups.power.nominal = 1000
    override.ups.realpower.nominal = 600

